# Generated by Django 3.1.7 on 2021-04-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210404_1212'),
        ('register', '0002_auto_20210404_1238'),
    ]

    operations = [
    ]
