# Generated by Django 3.1.7 on 2021-04-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_merge_20210404_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.user')),
                ('courses', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
            bases=('register.user',),
        ),
    ]
