# Generated by Django 3.1.7 on 2021-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=10, verbose_name='Poster')),
                ('date', models.DateTimeField(verbose_name='Date Posted')),
                ('title', models.TextField(verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
            ],
        ),
    ]
