# Generated by Django 3.1.7 on 2021-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum_id',
            field=models.CharField(default='General', max_length=20, verbose_name='Forum'),
        ),
    ]
