# Generated by Django 3.1.7 on 2021-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('user', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('course', models.TextField()),
            ],
        ),
    ]
