# Generated by Django 3.1.7 on 2021-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='file_size',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
