# Generated by Django 3.1.7 on 2021-05-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='course',
        ),
        migrations.AddField(
            model_name='rules',
            name='forum',
            field=models.CharField(default='General', max_length=20),
        ),
    ]
