# Generated by Django 3.1.7 on 2021-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_feedback_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='additional',
            field=models.BooleanField(default=False),
        ),
    ]
