# Generated by Django 3.1.7 on 2021-05-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_auto_20210525_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='content',
            new_name='rules',
        ),
    ]
